# Generated by Django 3.0.5 on 2020-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leave_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('AI', 'Artificial Intelligence and Machine Learning'), ('IOT', 'Cybersecurity and Internet of Things')], max_length=30)),
                ('mentor', models.CharField(choices=[('m1', 'mentor1'), ('m2', 'mentor2')], max_length=100)),
                ('leaves', models.IntegerField()),
                ('start_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
                ('reason', models.TextField()),
            ],
        ),
    ]
